package es.tipolisto.breeds.services;

public class ArrayDataSource {
    public static String[] catBreeds={
            "Abyssinian",
            "Aegean",
            "American Bobtail",
            "American Curl",
            "American Shorthair",
            "American Wirehair",
            "Arabian Mau",
            "Australiam Mist",
            "Balinese",
            "Bambino",
            "Bengal",
            "Birman",
            "Bombay",
            "British Longhair",
            "British Shorthair",
            "Burmese",
            "Burmilla",
            "California Spangled",
            "Chantilly-Tiffany",
            "Chartreux",
            "Chausie",
            "Cheetoh",
            "Colorpoint Shorthair",
            "Cornish Rex",
            "Cymric",
            "Cyprus",
            "Devon Rex",
            "Donskoy",
            "Dragon Li",
            "Egyptian Mau",
            "European Burmese",
            "Exotic Shorthair",
            "Havana Brown",
            "Himalayan"
    };



    public static String[] dogsBreeds={
            "Affenpinscher",
            "African",
            "Airedale",
            "Akita",
            "Appenzeller",
            "Shepherd Australian",
            "Bassenji",
            "Beagle",
            "Bluetick",
            "Borzoi",
            "Bouvier",
            "Boxer",
            "Brabancon",
            "Briard",
            "Norwegian Buhund",
            "Boston BUlldog",
            "English Bulldog",
            "French Bulldog",
            "Staffordshire Bullterrier",
            "Australian Cattledog",
            "Chihuahua",
            "Chow",
            "Clumber",
            "Cockapoo",
            "Border Collie",
            "Coonhound",
            "Cardigan Corgi",
            "Cotondetulear",
            "Dachshund",
            "Dalmatian",
            "Great Dane",
            "Scottish Deerhound",
            "Dhole",
            "Dingo",
            "Doberman"
    };
}
